"use client"

import { CircleDollarSign, Database, FileCheck2, Plus, ShieldCheck } from "lucide-react"
import Link from "next/link"
import { AppHeader, AppNotice } from "@/components/app-header"
import { DatasetCard, MetricCard, PassportRow } from "@/components/dataset-card"
import { useConsent } from "@/components/consent-provider"
import { formatNumber, receiptStatus } from "@/lib/consent-data"
import { OG_CHAIN } from "@/lib/chain-config"

export function DashboardPage() {
  const { datasets, licenses, wallet, networkReady } = useConsent()
  const owned = datasets.filter((dataset) => dataset.owner === "Local workspace" || Boolean(wallet && dataset.owner.toLowerCase() === wallet.toLowerCase()))
  const activeLicenses = licenses.filter((license) => receiptStatus(license) === "ACTIVE")
  const volume = activeLicenses.reduce((sum, license) => sum + license.price, 0)
  const activeDatasets = datasets.filter((dataset) => dataset.status === "active")
  return <main className="app-shell"><AppHeader app /><section className="page-section"><div className="section-heading-row"><div><span className="section-kicker">Workspace</span><h1>One clear view of your data rights.</h1><p>Browse passports, create licenses, and keep every receipt in one place.</p></div><Link href="/passports/new" className="button button-dark"><Plus size={16} /> Create passport</Link></div><div className="metric-grid page-metrics"><MetricCard icon={<Database size={18} />} label="Datasets" value={datasets.length.toString()} detail={`${owned.length} owned in this workspace`} /><MetricCard icon={<FileCheck2 size={18} />} label="Active licenses" value={activeLicenses.length.toString()} detail={`${licenses.length} total local receipts`} /><MetricCard icon={<CircleDollarSign size={18} />} label="Confirmed volume" value={`${formatNumber(volume)} 0G`} detail="Active paid receipts only" /></div><div className="overview-grid"><div className="panel passport-panel"><div className="panel-header"><div><span className="section-kicker">Latest passports</span><h3>Data, with terms attached.</h3></div><Link className="text-button" href="/marketplace">View marketplace <span>→</span></Link></div>{datasets.length === 0 ? <div className="panel-empty"><p>No passports yet.</p><Link href="/passports/new" className="text-button">Create the first passport →</Link></div> : <div className="passport-list">{datasets.slice(0, 4).map((dataset) => <PassportRow key={dataset.id} dataset={dataset} />)}</div>}</div><div className="panel quick-panel"><div className="panel-header"><div><span className="section-kicker">Network</span><h3>{networkReady ? "Connected to 0G Galileo." : "0G Galileo testnet."}</h3></div><ShieldCheck className="teal-icon" size={19} /></div><div className="network-panel-copy"><span className="network-dot" /><strong>Chain ID {Number.parseInt(OG_CHAIN.chainId, 16)}</strong><p>{wallet ? networkReady ? "Your wallet is on the correct network." : "Use Connect wallet to switch to the correct network." : "Connect a wallet to sign free licenses and pay for paid access."}</p><Link className="button button-outline button-small" href={OG_CHAIN.faucetUrl} target="_blank">Get testnet 0G</Link></div></div></div>{activeDatasets.length > 0 && <div className="dashboard-catalog"><div className="marketplace-toolbar"><div><span className="section-kicker">Catalog preview</span><h3>Browse what is available.</h3></div><Link className="text-button" href="/marketplace">Open marketplace →</Link></div><div className="dataset-grid">{activeDatasets.slice(0, 3).map((dataset) => <DatasetCard key={dataset.id} dataset={dataset} />)}</div></div>}</section><AppNotice /></main>
}
